default_ethereum_client_images:
  teku: docker.ethquokkaops.io/dh/ethpandaops/teku:data-column-withholding
  nethermind: docker.ethquokkaops.io/dh/ethpandaops/nethermind:fusaka-devnet-2
ethereum_node_mev_boost_enabled: false

teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --p2p-discovery-bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=PRUNE
  - --validators-graffiti={{ ansible_hostname }}
  - --logging=info
  - --Xlog-include-p2p-warnings-enabled
  - --metrics-block-timing-tracking-enabled
  - --ignore-weak-subjectivity-period-enabled
  - --rest-api-docs-enabled
  - --Xwithhold-data-column-sidecars-count=64