# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/spamoor.yaml.j2

syncoor-web:
  fullnameOverride: syncoor-web
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/ethpandaops/syncoor-web
            tag: master
            pullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi
  configMaps:
    config:
      enabled: true
      data:
        config.json: |
          {
            "directories": [
              {
                "name": "fusaka-devnet-3",
                "url": "https://syncoor-data.ethpandaops.io/devnets/fusaka-devnet-3"
              }
            ],
            "syncoorApiEndpoints": [
              {
                "name": "Syncoor",
                "url": "https://syncoor-api.fusaka-devnet-3.ethpandaops.io"
              }
            ]
          }
  ingress:
    main:
      className: ingress-nginx-public
      enabled: true
      hosts:
        - host: syncoor.fusaka-devnet-3.ethpandaops.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
