ethereum_cl_bootnodes:
  # - "{{ hostvars['bootnode-1']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-1']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-2']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-2']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-3']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-3']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-4']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-4']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-5']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-5']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-6']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-6']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-7']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-7']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-8']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-8']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-9']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-9']['ethereum_node_fact_cl_enr'] }}"
  # - "{{ hostvars['bootnode-10']['cl_bootnode_fact_enr'] }}"
  # - "{{ hostvars['bootnode-10']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lighthouse-besu-super-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lighthouse-nethermind-super-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lighthouse-nethermind-super-2']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lighthouse-reth-super-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lodestar-geth-super-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['prysm-geth-super-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['teku-geth-super-1']['ethereum_node_fact_cl_enr'] }}"
ethereum_el_bootnodes:
  # - "{{ hostvars['bootnode-1']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-2']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-3']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-4']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-5']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-6']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-7']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-8']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-9']['ethereum_node_fact_el_enode'] }}"
  # - "{{ hostvars['bootnode-10']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lighthouse-besu-super-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lighthouse-nethermind-super-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lighthouse-nethermind-super-2']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lighthouse-reth-super-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lodestar-geth-super-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['prysm-geth-super-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['teku-geth-super-1']['ethereum_node_fact_el_enode'] }}"

# role: ethpandaops.general.prometheus
prometheus_remote_push_url: https://victoriametrics-public.analytics.production.platform.ethpandaops.io/insert/1/prometheus
prometheus_remote_write_username: "{{ secret_prometheus_remote_write.username }}"
prometheus_remote_write_password: "{{ secret_prometheus_remote_write.password }}"
prometheus_config: |
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      instance: "{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      network: "{{ ethereum_network_name }}"
      testnet: "{{ ethereum_network_name }}"
      execution_client: "{{ ethereum_node_el }}"
      consensus_client: "{{ ethereum_node_cl }}"
      supernode: "{{ ethereum_node_cl_supernode_enabled | bool | default(false) }}"
  remote_write:
    - queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      url: {{ prometheus_remote_push_url }}
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_write_username }}
        password: {{ prometheus_remote_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["ethereum-metrics-exporter:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "consensus_node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["{{ vars[ethereum_node_cl + '_container_name'] }}:{{ ethereum_node_cl_ports_metrics }}"]
          labels:
            instance: "{{ inventory_hostname }}"

xatu_sentry_config_name: "{{ ethereum_network_name }}-{{ inventory_hostname }}"
xatu_sentry_config_server_address: "{{ secret_xatu_sentry.server_address }}"
xatu_sentry_config_server_auth_user: "{{ secret_xatu_sentry.user }}"
xatu_sentry_config_server_auth_password: "{{ secret_xatu_sentry.password }}"
xatu_sentry_config_network_name_override: "{{ ethereum_network_name }}"
xatu_sentry_container_networks: "{{ docker_networks_shared }}"
xatu_sentry_container_image: "{{ default_tooling_images.xatu_sentry }}"

xatu_sentry_container_command:
  - sentry
  - --config=/config.yaml

xatu_sentry_config:
  logging: "info"
  metricsAddr: ":9090"
  name: "{{ xatu_sentry_config_name }}"
  ntpServer: time.google.com
  ethereum:
    beaconNodeAddress: http://{{ vars[ethereum_node_cl + '_container_name'] }}:{{ethereum_node_cl_ports_http_beacon}}
    overrideNetworkName: "{{ xatu_sentry_config_network_name_override }}"
    beaconSubscriptions:
    - attestation
    - block
    - block_gossip
    - chain_reorg
    - finalized_checkpoint
    - head
    - voluntary_exit
    - contribution_and_proof
    - blob_sidecar
    - data_column_sidecar
  attestationData:
    enabled: false
  beaconCommittees:
    enabled: false
  forkChoice:
    enabled: false
  outputs:
  - config:
      address: "{{ xatu_sentry_config_server_address }}"
      headers:
        authorization: "Basic {{ (xatu_sentry_config_server_auth_user + ':' + xatu_sentry_config_server_auth_password) | b64encode }}"
      maxExportBatchSize: 32
      maxQueueSize: 1000000
      workers: 5
      tls: true
    filter:
      eventNames:
      - BEACON_API_ETH_V1_EVENTS_UNKNOWN
      - BEACON_API_ETH_V1_BEACON_COMMITTEE
      - BEACON_API_ETH_V1_EVENTS_BLOB_SIDECAR
      - BEACON_API_ETH_V1_EVENTS_BLOCK
      - BEACON_API_ETH_V1_EVENTS_BLOCK_V2
      - BEACON_API_ETH_V1_EVENTS_BLOCK_GOSSIP
      - BEACON_API_ETH_V1_EVENTS_CHAIN_REORG
      - BEACON_API_ETH_V1_EVENTS_CHAIN_REORG_V2
      - BEACON_API_ETH_V1_EVENTS_DATA_COLUMN_SIDECAR
      - BEACON_API_ETH_V1_EVENTS_FINALIZED_CHECKPOINT
      - BEACON_API_ETH_V1_EVENTS_FINALIZED_CHECKPOINT_V2
      - BEACON_API_ETH_V1_EVENTS_HEAD
      - BEACON_API_ETH_V1_EVENTS_HEAD_V2
      - BEACON_API_ETH_V1_EVENTS_VOLUNTARY_EXIT
      - BEACON_API_ETH_V1_EVENTS_VOLUNTARY_EXIT_V2
      - BEACON_API_ETH_V1_EVENTS_CONTRIBUTION_AND_PROOF
      - BEACON_API_ETH_V1_EVENTS_CONTRIBUTION_AND_PROOF_V2
      - BEACON_API_ETH_V1_VALIDATOR_ATTESTATION_DATA
      - MEMPOOL_TRANSACTION
      - MEMPOOL_TRANSACTION_V2
      - BEACON_API_ETH_V2_BEACON_BLOCK
      - BEACON_API_ETH_V2_BEACON_BLOCK_V2
    name: grpc-general
    type: xatu
  - config:
      address: "{{ xatu_sentry_config_server_address }}"
      headers:
        authorization: "Basic {{ (xatu_sentry_config_server_auth_user + ':' + xatu_sentry_config_server_auth_password) | b64encode }}"
      maxExportBatchSize: 128
      maxQueueSize: 1000000
      workers: 10
      tls: true
    filter:
      eventNames:
      - BEACON_API_ETH_V1_EVENTS_ATTESTATION
      - BEACON_API_ETH_V1_EVENTS_ATTESTATION_V2
    name: grpc-attestation
    type: xatu
